[package]
name = "rants"
version = "0.3.1"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
description = "An async NATS client library."
repository = "https://github.com/davidMcneil/rants"
keywords = ["client", "nats", "pub-sub", "messaging", "queue"]
categories = ["asynchronous", "api-bindings", "database-implementations", "network-programming", "parser-implementations"]
license = "MIT OR Apache-2.0"
edition = "2018"
exclude = ["rust-toolchain", ".vscode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.1"
futures = "0.3.1"
log = "0.4.8"
native-tls = "0.2.3"
nom = "5.0.1"
owning_ref = "0.4.0"
pin-utils = "0.1.0-alpha.4"
pin-project = "0.4.6"
rand = "0.7.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
tokio = { version = "0.2.1", features = ["dns", "io-util", "macros", "stream", "sync", "rt-core", "time", "tcp"] }
tokio-tls = "0.3.0"
tokio-util = { version = "0.2.0", features = ["codec"] }
uuid = { version = "0.7.4", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6.2"
hostname = "0.2.0"
tokio = { version = "0.2.1", features = ["process"] }
