[package]
name = "rants"
version = "0.3.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
description = "An async NATS client library."
repository = "https://github.com/davidMcneil/rants"
keywords = ["client", "nats", "pub-sub", "messaging", "queue"]
categories = ["asynchronous", "api-bindings", "database-implementations", "network-programming", "parser-implementations"]
license = "MIT OR Apache-2.0"
edition = "2018"
exclude = ["rust-toolchain", ".vscode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.19"
log = "0.4.8"
nom = "5.0.1"
owning_ref = "0.4.0"
pin-utils = "0.1.0-alpha.4"
rand = "0.7.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
uuid = { version = "0.7.4", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6.2"
