[package]
name = "gnat"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.17"
nom = "5.0.0"
parking_lot = "0.9.0"
url = "2.0.0"
rand = "0.7.0"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
tokio = "0.2.0-alpha.1"
