[package]
name = "rants"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.18"
log = "0.4.8"
nom = "5.0.1"
owning_ref = "0.4.0"
pin-utils = "0.1.0-alpha.4"
rand = "0.7.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
tokio = "0.2.0-alpha.3"
uuid = { version = "0.7.4", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6.2"
